// <auto-generated />
using System;
using BierpongProjectWebApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BierpongProjectWebApi.Migrations
{
    [DbContext(typeof(CustomDbContext))]
    partial class CustomDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BierpongProjectWebApi.Models.Entities.Friendship", b =>
                {
                    b.Property<Guid>("FriendshipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateAccepted")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateAccepted");

                    b.Property<DateTime>("DateRequested")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateRequested");

                    b.Property<Guid>("FriendUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId1")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("FriendshipId");

                    b.HasIndex("FriendUserId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId1");

                    b.ToTable("Friendships", (string)null);
                });

            modelBuilder.Entity("BierpongProjectWebApi.Models.Entities.Game", b =>
                {
                    b.Property<Guid>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid?>("ConfirmedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("confirmed_by");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("end_time");

                    b.Property<Guid?>("Player1Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("player1_id");

                    b.Property<int>("Player1Score")
                        .HasColumnType("int")
                        .HasColumnName("player1_score");

                    b.Property<Guid?>("Player2Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("player2_id");

                    b.Property<int>("Player2Score")
                        .HasColumnType("int")
                        .HasColumnName("player2_score");

                    b.Property<string>("Scoreline")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("scoreline");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_time");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<Guid>("WinnerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("winner_id");

                    b.HasKey("GameId");

                    b.HasIndex("Player1Id");

                    b.HasIndex("Player2Id");

                    b.ToTable("Game");
                });

            modelBuilder.Entity("BierpongProjectWebApi.Models.Entities.MatchHistory", b =>
                {
                    b.Property<int>("MatchHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MatchHistoryId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("date");

                    b.Property<int>("EloChange")
                        .HasColumnType("int")
                        .HasColumnName("elo_change");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("game_id");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("player_id");

                    b.Property<string>("Scoreline")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("scoreline");

                    b.HasKey("MatchHistoryId");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayerId");

                    b.ToTable("MatchHistory");
                });

            modelBuilder.Entity("BierpongProjectWebApi.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password");

                    b.Property<int>("Role")
                        .HasColumnType("int")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("BierpongProjectWebApi.Models.Entities.UserProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Bio");

                    b.Property<int>("ELO")
                        .HasColumnType("int")
                        .HasColumnName("ELO");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<string>("ProfilePictureUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ProfilePictureUrl");

                    b.HasKey("UserId");

                    b.ToTable("UserProfile");
                });

            modelBuilder.Entity("BierpongProjectWebApi.Models.Entities.Friendship", b =>
                {
                    b.HasOne("BierpongProjectWebApi.Models.Entities.UserProfile", "FriendUser")
                        .WithMany()
                        .HasForeignKey("FriendUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BierpongProjectWebApi.Models.Entities.UserProfile", "User")
                        .WithMany("Friendships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BierpongProjectWebApi.Models.Entities.User", null)
                        .WithMany("Friendships")
                        .HasForeignKey("UserId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FriendUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BierpongProjectWebApi.Models.Entities.Game", b =>
                {
                    b.HasOne("BierpongProjectWebApi.Models.Entities.User", "Player1")
                        .WithMany()
                        .HasForeignKey("Player1Id")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BierpongProjectWebApi.Models.Entities.User", "Player2")
                        .WithMany()
                        .HasForeignKey("Player2Id")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Player1");

                    b.Navigation("Player2");
                });

            modelBuilder.Entity("BierpongProjectWebApi.Models.Entities.MatchHistory", b =>
                {
                    b.HasOne("BierpongProjectWebApi.Models.Entities.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BierpongProjectWebApi.Models.Entities.User", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("BierpongProjectWebApi.Models.Entities.UserProfile", b =>
                {
                    b.HasOne("BierpongProjectWebApi.Models.Entities.User", "User")
                        .WithOne("UserProfile")
                        .HasForeignKey("BierpongProjectWebApi.Models.Entities.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BierpongProjectWebApi.Models.Entities.User", b =>
                {
                    b.Navigation("Friendships");

                    b.Navigation("UserProfile")
                        .IsRequired();
                });

            modelBuilder.Entity("BierpongProjectWebApi.Models.Entities.UserProfile", b =>
                {
                    b.Navigation("Friendships");
                });
#pragma warning restore 612, 618
        }
    }
}
